yarnPath: .yarn/releases/yarn-3.5.0.cjs

# This will fix the build error with @lerna/legacy-package-management
# packageExtensions:
#   "@lerna/legacy-package-management@*":
#     dependencies:
#       "@lerna/child-process": "*"
#       "js-yaml": "*"
#       "rimraf": "*"
#     peerDependencies:
#       "nx": "*"